services:
  # postgres service with limited shared mem and configurable password
  database:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: "/run/secrets/db_password"
    shm_size: 128mb
    secrets:
      - db_password

  backend:
    build:
      context: ./backend
    environment:
      RUST_LOG: info
    secrets:
      - db_password
    command:
      - "--db-host=database"
      - "--db-password-file=/run/secrets/db_password"
    depends_on:
      - database
    ports:
      - "8080:8080/tcp"

secrets:
  db_password:
    file: "db_password.txt"
