services:
  # postgres service with limited shared mem and configurable password
  database:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: "/run/secrets/db_password"
    shm_size: 128mb
    secrets:
      - db_password

  backend:
    build:
      context: ./backend
    secrets:
      - db_password
    command:
      - "--db-address=database:5432"
      - "--db-password=$(cat /run/secrets/db_password)"
      - "0.0.0.0:8080"
    depends_on:
      - database

secrets:
  db_password:
    file: "db_password.txt"
